config/routes.rb
Rails.application.routes.draw do
  get 'quiz_statuses/create'
  get 'sections/show'
  get 'courses/index'
  # get 'courses/show'
  get 'quiz_statuses/quizzquestions', to: "quiz_statuses#quizzquestions"
  devise_for :users
  root to: 'pages#home'
  get "/contacto", to: "pages#contacto"
  get "/nosotros", to: "pages#nosotros"
  get "courses/my_courses", to: "courses#my_courses"


  resources :courses, only: [:index, :show, :my_course] do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sections, only: [:show]
  resources :quizzes
  resources :quiz_statuses, only: [:create]
  resources :reviews, except: [:new, :create]
  resources :quiz_statuses, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses
  has_many :sections
  has_many :reviews
  has_one_attached :photo
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :section
  has_many :quiz_statuses


end

app/models/quiz_status.rb
class QuizStatus < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_one :quiz
  has_one_attached :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_courses
  has_many :reviews
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @courses = Course.all
    @user = current_user
  end

  def show
    @course = Course.find(params[:id])
  end

  def my_courses
    @courses = Course.all
    @user = current_user
  end
  private

  def course_params
    params.require(:course).permit(:titulo, :duracion, :detalle, :photo)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @courses = Course.all
  end

  def contactanos
  end

  def sobre_nosotros
  end
end

app/controllers/quiz_statuses_controller.rb
class QuizStatusesController < ApplicationController
  def create
    if params[:pregunta_a]["respuesta_1"] == "1" && params[:pregunta_b]["respuesta_2"] == "1" && params[:pregunta_c]["respuesta_3"] == "1"
      g = Section.where(id: params["current_section"]["r"].to_i + 1).first
      h = Section.where(id: params["current_section"]["r"].to_i).first

      if g
        # Hacer un contador con la cantidad de respuestas de buena( contador i =0)
        # Hacer un if para ver si el contador es mayor a cierto puntaje
        # Si es mayor lanzar un alert y que el botón de ese alert tenga el redirect
        # Y si no, lanzar alert nuevamente y que el bóton de ese alert te lleve al mismo modulo
        flash[:notice] = 'Has pasado el módulo, felicidades!'
        redirect_to section_path(g)
      else
        flash[:notice] = 'No hay más modulos, aprobaste este curso!'
        # Agregar un if al view, de que si usercourse.status = true, entonces agregar botoncito pequeño que diga hecho o aprobado
        # revisar si user_course funciona sino UserCourse
        @user = current_user.id
        @current_section = Section.find(params["current_section"]["r"].to_i)
        UserCourse.create(user_id:@user, course_id: @current_section.course_id, status: true)
        #  @curso = Section.find(params[:course_id])

        # @Actualizacion = current_user.user_course.status = true;
        # @Actualizacion.save
        redirect_to courses_path
      end
    else
      # si desaprobe =>
      flash[:notice] = 'No has pasado el modulo, vuelve a intentarlo!'

      redirect_to section_path(id: params["current_section"]["r"].to_i)
    end
  end
  # def quizzquestions

  #   respond_to do |format|
  #     format.js

  #   end
  # end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def show
    @quiz = Quiz.find(params[:id])
    @section = @quiz.section
  end

  def calcular
    # Agarrar resultados del formulario que llamó a esta función
    # Hacer calculo si aprueba o no aprueba
    # Hacer un if si redirige a X página u otra dependiendo el resultado
    # también se puede hacer en javascript directamente
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(user: current_user)
  end

  def new
    @review = Review.new
    @course = Course.find(params[:course_id])
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @course = Course.find(params[:course_id])
    @review.course = @course
    @review.user = current_user

    if @review.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @course = @review.course
    @review.update(review_params)

    redirect_to course_path(@course)
  end


  def destroy
    @review = Review.find(params[:id])
    @course = @review.course
    @review.destroy
    redirect_to courses_path
  end



  private

  def review_params
    params.require(:review).permit(:comentario, :rating)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find(params[:id])
    @quiz = @section.quiz
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="container row">
<div class="col-3">
 <ul class="list-unstyled ps-0 sticky-top">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed mt-3 fs-3" id="curso-link" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true"><i class="fas fa-caret-down fs-5"></i>
          Cursos
        </button>
        <hr>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small list-group">
            <% @courses.each do |course| %>
              <li class="p-2" id="curso-link"><i class="fas fa-graduation-cap"></i><a class="text-dark fs-7" href="#<%= course.id %>"> <%= course.titulo %></a></li>
              <%# no me deja toma el text-decoration-none %>
            <% end %>
          </ul>
        </div>
      </li>
    </ul>
</div>

<%# #Si el curso estatus está como true
  #entonces mostrar una carta que muestra que ya está hecho
  #Si no, entonces mostrar %>

<div class="col-9 mt-5 ml-2">
  <% @courses.each do |course| %>
    <div class="justify-content-end mr-3" id="<%= course.id %>">
      <div>


        <div class="card-product mb-5" id="absolute">
          <div class="foto fotoindex">
            <%= cl_image_tag course.photo.key%>
          </div>
          <div class="card-product-infos p-5">
            <div class="card-superior">
              <h2><%=course.titulo%></h2>
              <p> <strong>Duracion del curso </strong><%=course.duracion%> minutos</p>
            </div>
            <div class="card-inferior">
              <p><%= course.detalle.truncate(220) %></p>
            </div>
              <div>

              <%= link_to "Comenzar este curso", course_path(course), class: "btn btn-primary m-3 float-end" %>

            <% if user_signed_in? %>
             <% current_user.user_courses.each do |curso| %>
                <% if course.id == curso.course_id && curso.status%>
                  <%= image_tag("https://res.cloudinary.com/dydeg1evr/image/upload/v1653594877/development/Red_and_Gold_Transparent_Rosette_Ribbon_PNG_Clipart_jdpjcf.png", :id=>"relative") %>
                  <%= link_to "Dejar una review", new_course_review_path(course), class: "btn btn-primary m-3 float-end" %>

                <% end %>

              <% end %>
            <% end %>

              </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col text-center">
      <a href="/" class="btn btn-secondary btn-lg" id="botonVolver" role="button">Volver</a>
    </div>
  </div>
</div>

app/views/courses/my_courses.html.erb
<div class ="container mt-5">
    <h3 class="p-3">Mis cursos Realizados </h3>
    <% @courses.each do |course| %>
      <% if user_signed_in? %>
        <% current_user.user_courses.each do |curso| %>
          <% if course.id == curso.course_id && curso.status%>

            <div class="justify-content-end mr-3" id="<%= course.id %>">
              <div class="card-product mb-5" id="absolute">
                <div class="foto fotoindex">
                  <%= cl_image_tag course.photo.key%>
                </div>
                <div class="card-product-infos p-5">
                  <div class="card-superior">
                    <h2><%=course.titulo%></h2>
                    <p> <strong>Duracion del curso </strong><%=course.duracion%> minutos</p>
                  </div>
                  <div class="card-inferior">
                    <p><%= course.detalle.truncate(220) %></p>
                  </div>
                  <%= link_to "Rehacer curso", course_path(course), class: "btn btn-primary m-3 float-end" %>
                </div>
              </div>
            </div>




          <% end %>
        <% end %>
      <% end %>
    <% end %>


</div>

app/views/courses/show.html.erb
<div class="banner1">
  <div class="p-5 bg-dark text-white">
    <div class="row">
      <div class="col-6">
        <h1>
          <%= @course.titulo %>
        </h1>
        <p> <strong>Duracion del curso</strong>
          <%= @course.duracion %> hrs
        </p>
        <h6>
          <%= @course.detalle %>
        </h6>
      </div>
      <div class="col-6 text-center">
        <iframe src="https://www.youtube.com/embed/QgZiHmwBe_4" style="height: 300px" title="YouTube video" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="card1">
    <div class="row justify-content-between">
      <% @course.sections.each do |section| %>

        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
            <% unless user_signed_in? %>
              <%= link_to new_user_session_path do %>
              <section class="cards3d p-3">
                <figure class="card3d">
                  <figcaption class="card-title3d">
                    <%= image_tag "Educacion-financiera.jpg", style: "height: 150px; width: 100%; object-fit: contain;" %>
                      <div class="calle">
                        <h2 class="text-center">
                          <%= section.nombre.capitalize %></h2>
                        <p class="p-2 text-center"><%= section.descripcion %></p>
                      </div>
                  </figcaption>
                </figure>
              </section>
              <% end %>
            <% else %>
              <%= link_to section_path(section) do %>
              <section class="cards3d p-3">
                <figure class="card3d">
                  <figcaption class="card-title3d">
                    <%= image_tag "Educacion-financiera.jpg", style: "height: 150px; width: 100%; object-fit: contain;" %>
                      <div class="calle">
                        <h2 class="text-center">
                          <%= section.nombre.capitalize %></h2>
                        <p class="p-2 text-center"><%= section.descripcion %></p>
                      </div>
                  </figcaption>
                </figure>
              </section>
              <% end %>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

</div>

<div class="container mb-3">
  <% @course.reviews.each do |review| %>
    <!-- <p><%=  review.id %></p> -->
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card-review">
          <%# #Agregar source avatar estandar %>
            <img src='' class="avatar-large" />
            <div class="card-review-content text-center">
              <p><small><%= current_user.first_name %><%= current_user.last_name %></small></p>
              <% count=0 %>
              <% 5.times do %>
                <% if review.rating> count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
              <% count +=1 %>
              <% end %>
              <p>
              <%= review.comentario %>
              </p>
            </div>
            <br>


            <div class="card-review-actions text-center p-4">
              <% if review.user.email===current_user.email %>
                <a href="#">
                  <%=link_to "Editar review" , edit_review_path(review), method: :update %> <i
                      class="fas fa-pencil-alt"></i>
                </a>
                <a href="#">
                  <%=link_to "Eliminar" , review_path(review), method: :delete %> <i class="far fa-trash-alt"></i>
                </a>
                <% end %>
            </div>
        </div>
    </div>
    </div>
      <% end %>

</div>

<div class="container">
  <div class="row">
    <div class="col text-center">
      <a href="/courses" class="btn btn-secondary btn-lg" id="botonVolver" role="button">Volver</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeyondSchool</title>
    <%= favicon_link_tag "https://res.cloudinary.com/dydeg1evr/image/upload/v1653584107/development/favicon_1_cxtmzs.ico" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
  <script src="https://kit.fontawesome.com/4c742b4076.js" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="js/script.js"></script>

  <!-- JavaScript Bundle with Popper -->

</html>

app/views/pages/contactanos.html.erb
<h1>contactanos</h1>

app/views/pages/contacto.html.erb
<div class="container registrarse" style="width: 60%">
  <h2 class='text-center my-3'>Contacto</h2>
<div class="container">
    <div class="" id="form_container">
        <p>
           Escribe tu mensaje aqui. Te responderemos a la brevedad.
        </p>
        <form role="form" method="post" id="reused_form">

            <div class="row">
                <div class="col-sm-12 form-group my-2">
                    <label for="message">
                        Mensaje:</label>
                    <textarea class="form-control" type="textarea" id="message" name="message" maxlength="6000" rows="7"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 form-group my-2">
                    <label for="name">
                        Nombre y Apellido:</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="col-sm-6 form-group my-2">
                    <label for="email">
                        Email:</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-12 form-group my-2">
                    <button type="#" class="btn btn-primary" >Enviar</button>
                </div>
            </div>

        </form>
        <div id="success_message" style="width:100%; height:100%; display:none; ">
            <h3>Mensaje enviado!</h3>
        </div>
        <div id="error_message"
                style="width:100%; height:100%; display:none; ">
                    <h3>Error</h3>
                    Disculpa, tenemos un error al enviar el mensaje. Intenta nuevamente.

        </div>
    </div>
</div>
</div>

app/views/pages/home.html.erb
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="5000">
      <div class="banner text-lg-left" style="background-image: url('https://res.cloudinary.com/dydeg1evr/image/upload/v1652999187/development/background_xtnjjj.png')">
        <div class="container p-5">
          <div class="intento">
            <h1>Aprende de todo</h1>
            <p>Lo que no se enseña en el colegio y más</p>

            <% unless user_signed_in? %>
              <a href="#" class="btn-banner"> <%= link_to "Registrarme" , new_user_registration_path,class: 'btn btn-primary' %></a>
            <% end %>
            <a href="#" class="btn-banner"> <%= link_to "Ver todos los Cursos" , courses_index_path,class: 'btn btn-primary' %></a>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="5000">
      <div class="banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dgzbf6kp2/image/upload/c_scale,h_730,q_100,w_1213/v1653334439/development/home-real_i9vrcy.jpg);">
        <div class="container p-5">
          <h1>Aprende de todo</h1>
          <p>Lo que no se enseña en el colegio y más</p>

          <% unless user_signed_in? %>
            <a href="#" class="btn-banner"> <%= link_to "Registrarme" , new_user_registration_path,class: 'btn btn-primary' %></a>
          <% end %>
          <a href="#" class="btn-banner"> <%= link_to "Ver todos los Cursos" , courses_index_path,class: 'btn btn-primary' %></a>
        </div>
      </div>
    </div>
    <div class="carousel-item text-center" data-bs-interval="5000">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dgzbf6kp2/image/upload/c_scale,h_730,q_100,w_1213/v1653334449/development/home-real-3_ohvzlr.jpg);">
        <div class="container p-5">
          <h1>Aprende de todo</h1>
          <p>Lo que no se enseña en el colegio y más</p>

          <% unless user_signed_in? %>
            <a href="#" class="btn-banner"> <%= link_to "Registrarme" , new_user_registration_path,class: 'btn btn-primary' %></a>
          <% end %>
          <a href="#" class="btn-banner"> <%= link_to "Ver todos los Cursos" , courses_index_path,class: 'btn btn-primary' %></a>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<div class="small-container">
  <header class="text-center row flex-column middle-xs f-gap-medium">
  <h3>BeyondSchool</h3>
  <%# <img height="30" alt="Logo de Código Facilito" src="/assets/logo-cbf2a784ebee5d642aa7b8182df3e388d4feba0a23577eed1d2747fa05861f73.png">%>
  <p class="h1 f-text-48 no-margin">
  La plataforma
  <br>
  de aprendizaje para
  <br>
  ampliar tus conocimientos
  </p>
  <p class="h4 rb-normal no-margin-bottom f-grey-dark-text transparent-72">
  Aprende sobre finanzas, educación sexual, nutrición, nuevas tecnologías y muchos más.
  <strong>Desde tu casa.</strong>
  </p>
  </header>
</div>


<div class="f-padding-x f-padding-y-100 ds-section">
  <div class="main-container">
    <header class="text-center f-top f-bottom">
      <p class="h1 f-text-36 no-margin">Así funciona BeyondSchool</p>
      <div class="row text-center f-top" style="gap:25px;">
      <div class="col-sm no-padding col-xs-12"><div class="box"><div class="top-space">
      <%# <img height="129" src="/assets/svg/learn-code-69f62c8c13e07e612bcc085d1096c7a3cd1a51cf4188891698da1e2ea193385d.svg"> %>
      <i class="fa-brands fa-leanpub fa-2xl"></i>
      <p class="h1 f-top">Aprende desde 0</p>
      <p class="no-margin-top no-margin-bottom h4 rb-normal container-70">
      Ningun conocimiento es inalcanzable. Aprende los fundamentos básicos del curso que elijas.
      </p>
      </div>
      </div></div><div class="col-sm no-padding no-margin-xs col-xs-12"><div class="box"><div class="f-top-xs">
      <div class="top-space">
      <%# <img height="129" src="/assets/svg/learn-deeper-ee4e9763d6e82f3ffe4683d1c823fd211e3583e7a51f98bacd5dd168ae8801fa.svg"> %>
      <i class="far fa-clock fa-2xl"></i>
      <p class="h1 f-top">Estudia a tu ritmo y profundiza</p>
      <p class="no-margin-top no-margin-bottom h4 rb-normal container-70">
      ¿Quieres saber más que sólo los fundamentos? Profundiza el conocimiento más allá de lo básico con nuestra amplia gama de especializaciones.
      </p>
      </div>
      </div>
      </div></div><div class="col-sm no-padding col-xs-12"><div class="box"><div class="top-space">
      <%# <img height="129" src="/assets/svg/prepare-c3094c27c18eb693116c68ebcae88073ea94eaebadd215e9f14819557ac933e6.svg"> %>
      <i class="fas fa-tools fa-2xl"></i>
      <p class="h1 f-top">Adquiere herramientas útiles para tu vida cotidiana</p>
      <p class="no-margin-top no-margin-bottom h4 rb-normal container-70">
      Consigue las habilidades que necesitas para tener una visión mas conciente del mundo en el que vivimos.
      </p>
      </div>
      </div></div></div>
    </header>
  </div>
</div>

<div class="container">
  <div class="card1">
    <div class="row justify-content-between">
      <% @courses.each do |course| %>
        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <% unless user_signed_in? %>
            <%= link_to new_user_session_path do %>
              <section class="cards3d p-3">
                <figure class="card3d">
                  <figcaption class="card-title3d">
                    <% if course.photo.key %>
                      <%= cl_image_tag course.photo.key, style: "height: 150px; width: 100%; object-fit: contain;"%>
                    <% else %>
                      <%= image_tag "Educacion-financiera.jpg" %>
                    <% end %>
                  <div class="calle">
                    <h2 class="text-center" style="text-decoration: none"><%= course.titulo.capitalize %></h2>
                    <p class="text-center" style="text-decoration: none">Duración: <%= course.duracion %> hrs.</p>
                  </div>
                </figcaption>
            </figure>
          </section>
        <% end %>
      <% else %>
       <%= link_to course_path(course) do %>
        <section class="cards3d p-3">
          <figure class="card3d">
            <figcaption class="card-title3d">
              <% if course.photo.key %>
                <%= cl_image_tag course.photo.key, style: "height: 200px; width: 100%; object-fit: contain;"%>
              <% else %>
                <%= image_tag "Educacion-financiera.jpg" %>
              <% end %>
            <div class="calle">
              <h2 class="text-center"><%= course.titulo.capitalize %></h2>
              <p class="text-center">Duración: <%= course.duracion %> hrs.</p>
            </div>
          </figcaption>
        </figure>
      </section>
    <% end %>
    <% end %>
        </div>
  <% end %>
</div>
</div>
</div>
 </div>

app/views/pages/nosotros.html.erb
<h1>Nosotros</h1>

app/views/pages/sobre_nosotros.html.erb
<h1>sobre nosotros</h1>

app/views/quiz_statuses/create.html.erb
<h1>QuizStatuses#create</h1>
<p>Find me in app/views/quiz_statuses/create.html.erb</p>

app/views/quiz_statuses/quizzquestions.html.erb
<h1> hola mundo quizz questions </h1>

app/views/quiz_statuses/quizzquestions.js.erb
console.log("hola");

<h1> hola </h1>

app/views/reviews/edit.html.erb
<div id="feedback-form">
  <h2 class="header">¿Qué te pareció este curso?</h2>
  <div>
    <%= simple_form_for [@course, @review] do |f| %>
      <%= f.input :comentario %>
      <%= f.input :rating, as: :select, collection: [0,1,2,3,4,5], prompt: 'Califica este curso', label: false %>
      <%= f.submit "Crear review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div id="feedback-form">
  <h2 class="header">¿Qué te pareció este curso?</h2>
  <div>
    <%= simple_form_for [@course, @review] do |f| %>
      <%= f.input :comentario %>
      <%= f.input :rating, as: :select, collection: [0,1,2,3,4,5], prompt: 'Califica este curso', label: false %>
      <%= f.submit "Crear review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/sections/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="video-clase">
        <div class="ratio ratio-21x9">
          <iframe width='420' height='345' src=<%=@section.url_cloudinary%> title="YouTube video" allowfullscreen ></iframe>
        </div>
      </div>
      <div class="card my-4">
        <div class="container">
          <div class="row pt-2">
            <%# <div class="col-2"></div> %>
              <%# <div class="col-4"> %>
                <%# <h5 class="card-header">Sabias que?</h5> %>
                  <div class="card-body">
                    <h5 class="card-title"><strong><%= @section.course.titulo %> - <%= @section.nombre %></strong></h5>
                    <hr>
                    <p class="card-text"><%= @section.course.detalle %></p>
                    <a href="#"><%= link_to "Empezar quiz", quiz_path(@quiz), class: "btn btn-primary m-3 float-end", remote: true %></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
crossorigin="anonymous"></script> %>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1>BeyondSchool <strong>el conocimiento</strong> y <strong>las habilidades</strong> que necesitas!</h1>
    <p>Unete a nosotros, que aun hay mucho que aprender y descubrir.</p>
    <a class="btn btn-outline-secondary" href="#">Descrubrelo ahora</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>